// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl7hbmboMGdNQaDr8SOXGiaEK3uX_wMmM',
    appId: '1:161550571590:web:f43c52a5219419d6119247',
    messagingSenderId: '161550571590',
    projectId: 'musicapp-47928',
    authDomain: 'musicapp-47928.firebaseapp.com',
    storageBucket: 'musicapp-47928.firebasestorage.app',
    measurementId: 'G-ESBZTZ4VW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv-nYIiZn04IqQ8W_HOEA4NU344DB7Zwk',
    appId: '1:161550571590:android:ea7e17529163b6ac119247',
    messagingSenderId: '161550571590',
    projectId: 'musicapp-47928',
    storageBucket: 'musicapp-47928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw0dKYh1s6EmC6-1X0RGyn48nlFvV5QZU',
    appId: '1:161550571590:ios:ba529f15eb25ed40119247',
    messagingSenderId: '161550571590',
    projectId: 'musicapp-47928',
    storageBucket: 'musicapp-47928.firebasestorage.app',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw0dKYh1s6EmC6-1X0RGyn48nlFvV5QZU',
    appId: '1:161550571590:ios:ba529f15eb25ed40119247',
    messagingSenderId: '161550571590',
    projectId: 'musicapp-47928',
    storageBucket: 'musicapp-47928.firebasestorage.app',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl7hbmboMGdNQaDr8SOXGiaEK3uX_wMmM',
    appId: '1:161550571590:web:cfaccd17184c1cb5119247',
    messagingSenderId: '161550571590',
    projectId: 'musicapp-47928',
    authDomain: 'musicapp-47928.firebaseapp.com',
    storageBucket: 'musicapp-47928.firebasestorage.app',
    measurementId: 'G-G2D5ZTYQS0',
  );
}
